# Generated by Django 3.1.2 on 2020-10-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handcraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='picsofhandcraft')),
            ],
        ),
        migrations.DeleteModel(
            name='Samima',
        ),
        migrations.AlterField(
            model_name='bintu',
            name='img',
            field=models.ImageField(upload_to='picsofbuilding'),
        ),
        migrations.AlterField(
            model_name='isrita',
            name='img',
            field=models.ImageField(upload_to='picsofhuman'),
        ),
        migrations.AlterField(
            model_name='mithila',
            name='img',
            field=models.ImageField(upload_to='picsofcard'),
        ),
        migrations.AlterField(
            model_name='puspo',
            name='img',
            field=models.ImageField(upload_to='picsofnature'),
        ),
        migrations.AlterField(
            model_name='tonima',
            name='img',
            field=models.ImageField(upload_to='picsofplant'),
        ),
    ]
