# Generated by Django 3.1.2 on 2020-10-18 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0002_auto_20201018_1200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tonima',
            new_name='Plant',
        ),
    ]
