# Generated by Django 3.1.2 on 2020-10-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0003_auto_20201018_1202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mithila',
            new_name='Card',
        ),
    ]
