# Generated by Django 3.1.2 on 2020-10-18 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0004_auto_20201018_1205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bintu',
            new_name='Building',
        ),
        migrations.RenameModel(
            old_name='Isrita',
            new_name='Human',
        ),
        migrations.RenameModel(
            old_name='Puspo',
            new_name='Nature',
        ),
    ]
